name: Travel-Now CI-CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t laisapereira/travel-now .
      - name: Push Docker Image to DockerHub
        run: docker push laisapereira/travel-now:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from DockerHub
        run: docker pull laisapereira/travel-now:latest
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer laisapereira/travel-now
